//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptBuilderUtil.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScriptBuilderUtil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About program.
        /// </summary>
        public static string AboutProgramMenu {
            get {
                return ResourceManager.GetString("AboutProgramMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional injections:.
        /// </summary>
        public static string AdditionalInjectionsLabel {
            get {
                return ResourceManager.GetString("AdditionalInjectionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tags to result.
        /// </summary>
        public static string AddTagsToResultLabel {
            get {
                return ResourceManager.GetString("AddTagsToResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string CommonItem {
            get {
                return ResourceManager.GetString("CommonItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression:.
        /// </summary>
        public static string CompressionLabel {
            get {
                return ResourceManager.GetString("CompressionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyButton {
            get {
                return ResourceManager.GetString("CopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result field empty!.
        /// </summary>
        public static string ErrorEmptyResultField {
            get {
                return ResourceManager.GetString("ErrorEmptyResultField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard settings loaded..
        /// </summary>
        public static string ErrorSettingsFileNotFound {
            get {
                return ResourceManager.GetString("ErrorSettingsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected item in combobox..
        /// </summary>
        public static string ErrorUnexpectedComboBoxItem {
            get {
                return ResourceManager.GetString("ErrorUnexpectedComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include comments.
        /// </summary>
        public static string IncludeCommentsLabel {
            get {
                return ResourceManager.GetString("IncludeCommentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection parameters.
        /// </summary>
        public static string InjectionParametersGroup {
            get {
                return ResourceManager.GetString("InjectionParametersGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection site:.
        /// </summary>
        public static string InjectionSiteLabel {
            get {
                return ResourceManager.GetString("InjectionSiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string InstructionsMenu {
            get {
                return ResourceManager.GetString("InstructionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        public static string LengthLabel {
            get {
                return ResourceManager.GetString("LengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string MaximumItem {
            get {
                return ResourceManager.GetString("MaximumItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation tags.
        /// </summary>
        public static string NavigationTagsGroup {
            get {
                return ResourceManager.GetString("NavigationTagsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root file:.
        /// </summary>
        public static string RootFileLabel {
            get {
                return ResourceManager.GetString("RootFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string RunButtom {
            get {
                return ResourceManager.GetString("RunButtom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save first root comment.
        /// </summary>
        public static string SaveFirstMainCommentLabel {
            get {
                return ResourceManager.GetString("SaveFirstMainCommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script beginning:.
        /// </summary>
        public static string ScriptBeginningLabel {
            get {
                return ResourceManager.GetString("ScriptBeginningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script ending:.
        /// </summary>
        public static string ScriptEndingLabel {
            get {
                return ResourceManager.GetString("ScriptEndingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewMenu {
            get {
                return ResourceManager.GetString("ViewMenu", resourceCulture);
            }
        }
    }
}
