//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptBuilderUtil.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScriptBuilderUtil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string ButtonBuild {
            get {
                return ResourceManager.GetString("ButtonBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ButtonCopy {
            get {
                return ResourceManager.GetString("ButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CompressinDescriptionBuild {
            get {
                return ResourceManager.GetString("CompressinDescriptionBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CompressinDescriptionHard {
            get {
                return ResourceManager.GetString("CompressinDescriptionHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CompressinDescriptionLight {
            get {
                return ResourceManager.GetString("CompressinDescriptionLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CompressinDescriptionMaximum {
            get {
                return ResourceManager.GetString("CompressinDescriptionMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only build.
        /// </summary>
        public static string CompressionBuildItem {
            get {
                return ResourceManager.GetString("CompressionBuildItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string CompressionHardItem {
            get {
                return ResourceManager.GetString("CompressionHardItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string CompressionLightItem {
            get {
                return ResourceManager.GetString("CompressionLightItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorLabel {
            get {
                return ResourceManager.GetString("ErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters have been not saved. Do you want stay in application?{0}.
        /// </summary>
        public static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on saving settings.
        /// </summary>
        public static string ErrorSavingCaption {
            get {
                return ResourceManager.GetString("ErrorSavingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type of build..
        /// </summary>
        public static string ErrorUnexpectedComboBoxItem {
            get {
                return ResourceManager.GetString("ErrorUnexpectedComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional injections:.
        /// </summary>
        public static string LabelAdditionalInjections {
            get {
                return ResourceManager.GetString("LabelAdditionalInjections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tags to result.
        /// </summary>
        public static string LabelAddTagsToResult {
            get {
                return ResourceManager.GetString("LabelAddTagsToResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression:.
        /// </summary>
        public static string LabelCompression {
            get {
                return ResourceManager.GetString("LabelCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include comments.
        /// </summary>
        public static string LabelIncludeComments {
            get {
                return ResourceManager.GetString("LabelIncludeComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        public static string LabelLength {
            get {
                return ResourceManager.GetString("LabelLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root file:.
        /// </summary>
        public static string LabelRootFile {
            get {
                return ResourceManager.GetString("LabelRootFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save first root comment.
        /// </summary>
        public static string LabelSaveFirstMainComment {
            get {
                return ResourceManager.GetString("LabelSaveFirstMainComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About program.
        /// </summary>
        public static string MenuAboutProgram {
            get {
                return ResourceManager.GetString("MenuAboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string MenuInstructions {
            get {
                return ResourceManager.GetString("MenuInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection parameters.
        /// </summary>
        public static string TabInjectionParameters {
            get {
                return ResourceManager.GetString("TabInjectionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation tags.
        /// </summary>
        public static string TabTagNavigation {
            get {
                return ResourceManager.GetString("TabTagNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection tag:.
        /// </summary>
        public static string TagInjectionLabel {
            get {
                return ResourceManager.GetString("TagInjectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script beginning:.
        /// </summary>
        public static string TagScriptBeginningLabel {
            get {
                return ResourceManager.GetString("TagScriptBeginningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script ending:.
        /// </summary>
        public static string TagScriptEndingLabel {
            get {
                return ResourceManager.GetString("TagScriptEndingLabel", resourceCulture);
            }
        }
    }
}
